export const MAP_THEME = {
  effect: {
    toneMappingExposure: 0.7,
    outline: {
      enabled: true,
      ghostExtrudedPolygons: false,
      thickness: 0.0034,
      color: '#898989',
    },
    bloom: {
      enabled: true,
      strength: 0.1,
      threshold: 0.1,
      radius: 0.1,
    },
    vignette: {
      enabled: true,
      offset: 1.2,
      darkness: 1.2,
    },
    sepia: {
      enabled: false,
      amount: 0.44,
    },
  },
  sky: {
    type: 'gradient',
    topColor: '#83AEEB',
    bottomColor: '#83AEEB',
    groundColor: '#83AEEB',
    monomialPower: 1,
  },
  fog: {
    color: '#262829',
    startRatio: 0.8,
  },
  clearColor: '#797662', // soil color
  lights: [
    {
      type: 'ambient',
      color: '#FFFFFF',
      name: 'ambientLight',
      intensity: 0.3,
    },
    {
      type: 'directional',
      color: '#FFFFFF',
      castShadow: true,
      name: 'light1',
      intensity: 1.4,
      direction: {
        x: -7,
        y: -7,
        z: 12,
      },
    },
  ],
  style: [
    {
      description: 'pier',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['any', ['==', ['get', 'class'], 'pier']],
      ],
      technique: 'solid-line',
      renderOrder: 10,
      final: true,
      color: '#333334',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        1.5,
        14,
        1.2,
        15,
        0.9,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'residential - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['!=', ['get', 'class'], 'rail'],
        ['==', ['get', 'class'], 'minor'],
      ],
      technique: 'solid-line',
      renderOrder: 11,
      color: '#000',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        10,
        42,
        11,
        28,
        12,
        18,
        13,
        7,
        14,
        3.5,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'residential - fill',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['!=', ['get', 'class'], 'rail'],
        ['==', ['get', 'class'], 'minor'],
      ],
      technique: 'solid-line',
      renderOrder: 11.3,
      color: '#655f41',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        10,
        38,
        11,
        24,
        12,
        13,
        13,
        5,
        14,
        3,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'residential - text',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['!=', ['get', 'class'], 'rail'],
        ['==', ['get', 'class'], 'minor'],
      ],
      technique: 'none',
      renderOrder: 12,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 0,
      priority: 15,
      fadeNear: 0.8,
      fadeFar: 0.9,
    },
    {
      description: 'secondary',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['!=', ['get', 'class'], 'rail'],
        ['==', ['get', 'class'], 'major_road'],
      ],
      technique: 'text',
      renderOrder: 12,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 16,
      priority: 15,
      fadeNear: 0.8,
      fadeFar: 0.9,
    },
    {
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['get', 'class'], 'secondary'],
      ],
      technique: 'solid-line',
      renderOrder: 15.3,
      secondaryRenderOrder: 10.3,
      final: true,
      color: '#655f41',
      secondaryColor: '#655f41',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        7,
        180,
        8,
        110,
        9,
        45,
        10,
        30,
        11,
        20,
        12,
        12,
        13,
        7,
        14,
        5,
      ],
      secondaryWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        7,
        180,
        8,
        110,
        9,
        45,
        10,
        30,
        11,
        20,
        12,
        16,
        13,
        9,
        14,
        5.5,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'tertiary',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['in', ['get', 'class'], ['literal', ['primary', 'tertiary']]],
      ],
      technique: 'text',
      renderOrder: 13,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 0,
      priority: 20,
      fadeNear: 0.8,
      fadeFar: 0.9,
    },
    {
      description: 'tertiary - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['in', ['get', 'class'], ['literal', ['primary', 'tertiary']]],
      ],
      technique: 'solid-line',
      renderOrder: 10.3,
      color: '#000',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        6,
        550,
        7,
        300,
        8,
        100,
        9,
        70,
        10,
        38,
        11,
        24,
        12,
        14,
        13,
        7,
        14,
        4.5,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'service - inline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['get', 'class'], 'service'],
        [
          'in',
          ['get', 'service'],
          [
            'literal',
            [
              'spur',
              'yard',
              'siding',
              'crossover',
              'driveway',
              'alley',
              'parking_aisle',
            ],
          ],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 10.3,
      color: '#686D71',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        6,
        550,
        7,
        300,
        8,
        100,
        9,
        70,
        10,
        38,
        11,
        24,
        12,
        14,
        13,
        7,
        14,
        4.5,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'service - surface',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['get', 'class'], 'service'],
        [
          'in',
          ['get', 'surface'],
          [
            'literal',
            [
              'paved',
              'asphalt',
              'cobblestone',
              'concrete',
              'concrete:lanes',
              'concrete:plates',
              'metal',
              'paving_stones',
              'sett',
              'unhewn_cobblestone',
              'wood',
            ],
          ],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 10.3,
      color: '#686D71',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        6,
        550,
        7,
        300,
        8,
        100,
        9,
        70,
        10,
        38,
        11,
        24,
        12,
        14,
        13,
        7,
        14,
        4.5,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'tertiary - fill',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['in', ['get', 'class'], ['literal', ['primary', 'tertiary']]],
      ],
      technique: 'solid-line',
      renderOrder: 15.3,
      final: true,
      color: '#5CA5AF',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        5,
        830,
        6,
        410,
        7,
        220,
        8,
        100,
        9,
        50,
        10,
        30,
        11,
        20,
        12,
        11,
        13,
        6,
        14,
        4,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'primary',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'any',
          ['==', ['get', 'class'], 'motorway'],
          ['==', ['get', 'class'], 'primary'],
        ],
      ],
      technique: 'text',
      renderOrder: 10,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 0,
      priority: 25,
      fadeNear: 0.8,
      fadeFar: 0.9,
    },
    {
      description: 'primary - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'any',
          ['==', ['get', 'class'], 'motorway'],
          ['==', ['get', 'class'], 'primary'],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 10.4,
      color: '#000',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        6,
        700,
        7,
        400,
        8,
        200,
        9,
        90,
        10,
        50,
        11,
        33,
        12,
        16,
        13,
        11,
        14,
        6.5,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'primary - fill',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'any',
          ['==', ['get', 'class'], 'motorway'],
          ['==', ['get', 'class'], 'primary'],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 15.4,
      final: true,
      color: '#686D71',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        5,
        830,
        6,
        550,
        7,
        300,
        8,
        150,
        9,
        70,
        10,
        35,
        11,
        22,
        12,
        12,
        13,
        8,
        14,
        6,
      ],
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'ferry',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['!=', ['get', 'class'], 'rail'],
        ['==', ['get', 'class'], 'ferry'],
      ],
      technique: 'text',
      renderOrder: 10,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 0,
      priority: 25,
      fadeNear: 0.8,
      fadeFar: 0.9,
    },
    {
      description: 'TODO',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'in',
          ['get', 'class'],
          ['literal', ['class', 'parking_aisle', 'drive_through']],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 10,
      final: true,
      color: '#5E6062',
      lineWidth: 5,
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'TODO',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'in',
          ['get', 'class'],
          ['literal', ['class', 'parking_aisle', 'drive_through']],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 10,
      final: true,
      color: '#5E6062',
      lineWidth: 5,
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'pedestrian - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'any',
          [
            'in',
            ['get', 'class'],
            ['literal', ['pedestrian', 'path', 'footway']],
          ],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 10.3,
      color: '#000',
      lineWidth: 1.5,
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'pedestrian - fill',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'any',
          [
            'in',
            ['get', 'class'],
            ['literal', ['pedestrian', 'path', 'footway']],
          ],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 14,
      color: '#438766',
      lineWidth: 1.3,
      fadeNear: 0.8,
      fadeFar: 0.9,
      clipping: false,
    },
    {
      description: 'pedestrian - text',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        [
          'any',
          [
            'in',
            ['get', 'class'],
            ['literal', ['pedestrian', 'path', 'footway']],
          ],
        ],
      ],
      technique: 'text',
      renderOrder: 12,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 0,
      priority: 15,
      fadeNear: 0.8,
      fadeFar: 0.9,
    },
    {
      description: 'tram',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['geometry-type'], 'LineString'],
        ['in', ['get', 'class'], ['literal', ['rail', 'light_rail', 'tram']]],
        ['==', ['get', 'class'], 'tram'],
      ],
      technique: 'solid-line',
      renderOrder: 50,
      final: true,
      color: '#57585B',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        1.5,
        16,
        0.75,
        17,
        0.4,
      ],
    },
    {
      description: 'industrial_railway',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['geometry-type'], 'LineString'],
        ['in', ['get', 'class'], ['literal', ['rail', 'light_rail', 'tram']]],
        [
          'in',
          ['get', 'service'],
          ['literal', ['siding', 'industrial', 'yard', 'spur', 'crossover']],
        ],
      ],
      technique: 'solid-line',
      renderOrder: 5,
      final: true,
      color: '#606164',
    },
    {
      description: 'Railway+S-Bahn background - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['geometry-type'], 'LineString'],
        ['in', ['get', 'class'], ['literal', ['rail', 'light_rail', 'tram']]],
        ['!', ['get', 'is_tunnel']],
      ],
      technique: 'solid-line',
      renderOrder: 5.2,
      color: '#6A6C6F',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        3.5,
        14.6,
        1.5,
        15,
        0.5,
      ],
    },
    {
      description: 'Railway+S-Bahn background - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['geometry-type'], 'LineString'],
        ['in', ['get', 'class'], ['literal', ['rail', 'light_rail', 'tram']]],
        ['get', 'is_tunnel'],
      ],
      technique: 'solid-line',
      renderOrder: 5.1,
      color: '#6A6C6F',
      lineWidth: ['interpolate', ['linear'], ['zoom'], 13, 3.5, 21, 2.5],
    },
    {
      description: 'Railway+S-Bahn dashes',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['geometry-type'], 'LineString'],
        ['in', ['get', 'class'], ['literal', ['rail', 'light_rail', 'tram']]],
        ['!', ['get', 'is_tunnel']],
      ],
      technique: 'dashed-line',
      renderOrder: 5.25,
      final: true,
      color: '#7B7E81',
      dashSize: [
        'step',
        ['zoom'],
        30,
        11,
        20,
        12,
        12,
        13,
        7,
        14,
        4,
        15,
        2,
        20,
        1,
      ],
      gapSize: [
        'step',
        ['zoom'],
        100,
        11,
        55,
        12,
        50,
        13,
        40,
        14,
        25,
        15,
        12,
        20,
        8,
      ],
      lineWidth: ['interpolate', ['linear'], ['zoom'], 13, 2.75, 21, 1.75],
    },
    {
      description: 'Railway+S-Bahn dashes',
      when: [
        'all',
        ['==', ['get', '$layer'], 'transportation'],
        ['==', ['geometry-type'], 'LineString'],
        ['in', ['get', 'class'], ['literal', ['rail', 'light_rail', 'tram']]],
        ['get', 'is_tunnel'],
      ],
      technique: 'dashed-line',
      renderOrder: 5.15,
      final: true,
      color: '#454648',
      dashSize: [
        'step',
        ['zoom'],
        100,
        11,
        40,
        12,
        24,
        13,
        30,
        14,
        25,
        15,
        15,
        16,
        8,
      ],
      gapSize: [
        'step',
        ['zoom'],
        100,
        11,
        40,
        12,
        24,
        13,
        30,
        14,
        25,
        15,
        15,
        16,
        8,
      ],
      lineWidth: ['interpolate', ['linear'], ['zoom'], 13, 2.75, 14, 1.75],
    },
    {
      description: 'ocean',
      when: [
        'all',
        ['==', ['get', '$layer'], 'water'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'ocean'],
      ],
      technique: 'standard',
      color: '#212e2e',
      // attr: {
      //   // map: '/static/texture/ocean.jpg',
      //   color: '#176172',
      //   mapProperties: {
      //     repeatU: 5,
      //     repeatV: 5,
      //     wrapS: 'repeat',
      //     wrapT: 'repeat',
      //   },
      //   textureCoordinateType: 'tile-space',
      // },
    },
    {
      description: 'water',
      when: [
        'all',
        ['==', ['get', '$layer'], 'water'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'lake'],
      ],
      technique: 'fill',
      renderOrder: 5,
      color: '#3D6173',
    },
    {
      description: 'water',
      when: ['==', ['get', '$layer'], 'water'],
      technique: 'text',
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      opacity: 0.5,
      size: 0,
    },
    {
      description: 'country border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'country'],
      ],
      technique: 'solid-line',
      renderOrder: 5,
      color: '#373A3C',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        1,
        5000,
        2,
        4000,
        3,
        3500,
        4,
        2500,
        5,
        1500,
        6,
        1000,
        7,
        500,
        8,
        250,
        9,
        125,
        10,
        60,
        11,
        40,
        12,
        20,
        13,
        10,
        14,
        5,
      ],
    },
    {
      description: 'country border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'country'],
      ],
      technique: 'solid-line',
      renderOrder: 5,
      color: '#2E3234',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        2,
        1000,
        3,
        700,
        4,
        500,
        5,
        250,
        6,
        110,
        7,
        45,
        8,
        25,
        9,
        15,
        10,
        10,
        11,
        7.5,
        12,
        5,
        13,
        2.5,
        14,
        1,
      ],
    },
    {
      description: 'country border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'country'],
      ],
      technique: 'text',
      priority: 100,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 12.8,
    },
    {
      description: 'disputed border line',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        [
          'in',
          ['get', 'class'],
          [
            'literal',
            [
              'disputed',
              'indefinite',
              'indeterminate',
              'lease_limit',
              'line_of_control',
              'overlay_limit',
            ],
          ],
        ],
      ],
      technique: 'dashed-line',
      renderOrder: 4.1,
      color: '#2E3234',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        2,
        4000,
        3,
        2600,
        4,
        1500,
        5,
        1000,
        6,
        720,
        7,
        520,
        8,
        270,
        9,
        140,
        10,
        90,
        11,
        60,
        12,
        30,
        13,
        15,
        14,
        10,
        15,
        5,
        16,
        2,
      ],
      dashSize: [
        'interpolate',
        ['cubic'],
        ['zoom'],
        10,
        1024,
        11,
        512,
        12,
        256,
        13,
        128,
        14,
        64,
      ],
      gapSize: [
        'interpolate',
        ['cubic'],
        ['zoom'],
        10,
        512,
        11,
        256,
        12,
        128,
        13,
        64,
        14,
        32,
      ],
    },
    {
      description: 'disputed border line - text',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        [
          'in',
          ['get', 'class'],
          [
            'literal',
            [
              'disputed',
              'indefinite',
              'indeterminate',
              'lease_limit',
              'line_of_control',
              'overlay_limit',
            ],
          ],
        ],
      ],
      technique: 'text',
      priority: 100,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 12.8,
    },
    {
      description: 'region border - outline',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'region'],
      ],
      technique: 'solid-line',
      renderOrder: 4.1,
      color: '#7C7C7C',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        2,
        600,
        3,
        300,
        4,
        150,
        5,
        100,
        6,
        60,
        7,
        30,
        8,
        20,
        9,
        12,
        10,
        8,
        11,
        5,
        12,
        3,
        13,
        2,
        14,
        1,
      ],
    },
    {
      description: 'region border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'region'],
      ],
      technique: 'solid-line',
      renderOrder: 4.1,
      color: '#7C7C7C',
      lineWidth: [
        'interpolate',
        ['linear'],
        ['zoom'],
        2,
        600,
        3,
        300,
        4,
        150,
        5,
        100,
        6,
        60,
        7,
        30,
        8,
        20,
        9,
        12,
        10,
        8,
        11,
        5,
        12,
        3,
        13,
        2,
        14,
        1,
      ],
    },
    {
      description: 'region border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'region'],
      ],
      technique: 'text',
      priority: 90,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 12.8,
    },
    {
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundaries'],
        ['==', ['geometry-type'], 'Point'],
      ],
      technique: 'text',
      renderOrder: 7,
      color: '#999999',
      backgroundColor: '#141414',
      backgroundOpacity: 0.5,
      size: 27.2,
      priority: 200,
    },
    {
      description: 'urban',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        // ['==', ['get', 'class'], 'urban'],
      ],
      technique: 'fill',
      renderOrder: 0,
      opacity: 0.5,
      color: '#706d5a',
    },
    {
      description: 'urban area',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'urban_area'],
      ],
      technique: 'none',
      renderOrder: 0.1,
      color: '#3B3E45',
    },
    {
      description: 'park',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landcover'],
        ['==', ['geometry-type'], 'Polygon'],
        [
          'in',
          ['get', 'class'],
          [
            'literal',
            [
              'nature',
              'forest',
              'park',
              'wood',
              'natural_wood',
              'grass',
              'meadow',
              'village_green',
              'dog_park',
              'garden',
              'nature_reserve',
              'protected_area',
            ],
          ],
        ],
      ],

      technique: 'standard',
      color: '#5a6b21',
      // color: '#4C7A4F', // old theme
      // color: '#243d10',
    },
    {
      description: 'runway',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'runway'],
      ],
      technique: 'fill',
      renderOrder: 20,
      final: true,
      color: '#2E3036',
    },
    {
      description: 'runway',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'runway'],
      ],
      technique: 'fill',
      renderOrder: 20,
      final: true,
      color: '#2E3036',
    },
    {
      description: 'national_park',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'national_park'],
      ],
      technique: 'fill',
      renderOrder: 1,
      color: '#5a6b21',
    },
    {
      description: 'pitch',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'pitch'],
      ],
      technique: 'fill',
      renderOrder: 1,
      color: '#373A40',
    },
    {
      description: 'hospital',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'hospital'],
      ],
      technique: 'fill',
      renderOrder: 0.1,
      color: '#373A40',
    },
    {
      description: 'cemetery',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'cemetery'],
      ],
      technique: 'fill',
      renderOrder: 0.1,
      color: '#373A40',
    },
    {
      description: 'bridge',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'bridge'],
      ],
      technique: 'fill',
      renderOrder: 1,
      color: '#ff0000',
    },
    {
      description: 'zoo',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        [
          'in',
          ['get', 'class'],
          ['literal', ['sport', 'sports_centre', 'attraction', 'zoo']],
        ],
      ],
      technique: 'fill',
      renderOrder: 1,
      color: '#373A40',
    },
    {
      description: 'religion',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'religion'],
      ],
      technique: 'fill',
      renderOrder: 1,
      color: '#373A40',
    },
    {
      description: 'industrial',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        [
          'in',
          ['get', 'class'],
          [
            'literal',
            ['common', 'surface', 'commercial', 'military', 'industrial'],
          ],
        ],
      ],
      technique: 'fill',
      renderOrder: 0,
      color: '#646050',
    },
    {
      description: 'farmyard',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        [
          'in',
          ['get', 'class'],
          [
            'literal',
            ['animal', 'aviary', 'zoo', 'farm', 'farmland', 'farmyard'],
          ],
        ],
      ],
      technique: 'fill',
      renderOrder: 0,
      color: '#373A40',
    },
    {
      description: 'beach',
      when: [
        'all',
        ['==', ['get', '$layer'], 'landuse'],
        ['==', ['geometry-type'], 'Polygon'],
        [
          'any',
          ['==', ['get', 'class'], 'beach'],
          ['$=', ['get', 'class'], '_site'],
        ],
      ],
      technique: 'fill',
      renderOrder: 1,
      color: '#373A40',
    },
    {
      description: 'Earth layer',
      when: [
        'all',
        ['==', ['get', '$layer'], 'earth'],
        ['!=', ['get', 'class'], 'island'],
      ],
      technique: 'text',
      priority: ['interpolate', ['linear'], ['zoom'], 2, 120, 3, 100, 4, 60],
      color: '#ff0000',
      backgroundColor: '#ff0000',
      fontVariant: 'SmallCaps',
      opacity: 0.6,
    },
    {
      description: 'Earth layer',
      when: [
        'all',
        ['==', ['get', '$layer'], 'earth'],
        ['==', ['get', 'class'], 'island'],
      ],
      technique: 'text',
      color: '#3B3E45',
      backgroundColor: '#000000',
      opacity: 0.6,
      size: 16,
    },
    {
      description: 'building_geometry',
      when: [
        'all',
        ['==', ['get', '$layer'], 'building'],
        ['==', ['get', '$geometryType'], 'polygon'],
        ['==', ['get', 'hide_3d'], null],
      ],
      enabled: [
        'none',
        [
          'in',
          ['get', 'poi_code'],
          ['get', '3d_codes', ['dynamic-properties']],
        ],
      ],
      technique: 'extruded-polygon',
      height: ['get', 'render_height'],
      floorHeight: ['get', 'render_min_height'],
      minZoomLevel: 10,
      // renderOrder: 2000,
      color: '#444232',
      // color: '#c0f4fa',
      // color: '#726f67',
      // opacity: 1,
      defaultHeight: 10,
      roughness: 2,
      // emissive: 'red',
      // emissive: '#93bfc3',
      // emissiveIntensity: 0.1,
      footprint: true,
      // maxSlope: 0.8799999999999999,
      lineWidth: 0.2,
      // lineColor: '#A4B0BD',
      lineColor: '#5f5b44',
      lineColorMix: 0.1,
      fadeNear: 0.1,
      fadeFar: 1,
      lineFadeNear: 1,
      // lineFadeFar: 0.7,
    },
    {
      description: 'building_geometry',
      when: [
        'all',
        ['==', ['get', '$layer'], 'building'],
        ['==', ['get', '$geometryType'], 'polygon'],
        ['==', ['get', 'hide_3d'], null],
        ['in', ['get', 'poi_code'], ['literal', ['']]],
      ],
      enabled: [
        'none',
        [
          'in',
          ['get', 'poi_code'],
          ['get', '3d_codes', ['dynamic-properties']],
        ],
      ],
      technique: 'extruded-polygon',
      height: ['get', 'render_height'],
      floorHeight: ['get', 'render_min_height'],
      minZoomLevel: 14,
      renderOrder: 2000,
      color: '#000',
      opacity: 0.5,
      defaultHeight: 1,
      roughness: 1,
      emissive: '#EDEDED',
      emissiveIntensity: 0.1,
      footprint: true,
      maxSlope: 0.8799999999999999,
      lineWidth: 0.1,
      lineColor: '#A4B0BD',
      lineColorMix: 0.1,
      fadeNear: 0.1,
      fadeFar: 1,
      lineFadeNear: 1,
      lineFadeFar: 0.7,
    },
    {
      description: 'building_geometry select',
      when: [
        'all',
        ['==', ['get', '$layer'], 'building'],
        ['==', ['get', '$geometryType'], 'polygon'],
        ['==', ['get', 'hide_3d'], null],
      ],
      enabled: [
        'in',
        ['get', 'poi_code'],
        ['get', 'selection', ['dynamic-properties']],
      ],
      technique: 'extruded-polygon',
      height: ['get', 'render_height'],
      floorHeight: ['get', 'render_min_height'],
      minZoomLevel: 14,
      renderOrder: 2000,
      color: '#dea25b',
      opacity: 0.6,
      defaultHeight: 1,
      roughness: 1,
      emissive: '#dea25b',
      emissiveIntensity: 0.1,
      footprint: true,
      maxSlope: 0.8799999999999999,
      lineWidth: 2,
      lineColor: '#9EFFFF',
      lineColorMix: 0.1,
      fadeNear: 0.1,
      fadeFar: 1,
      lineFadeNear: 1,
      lineFadeFar: 0.7,
    },
    {
      description: 'building_address',
      when: [
        'all',
        ['==', ['get', '$layer'], 'buildings'],
        ['==', ['geometry-type'], 'Point'],
        ['==', ['get', 'class'], 'address'],
      ],
      technique: 'text',
      minZoomLevel: 18,
      renderOrder: 100,
      color: '#131313',
      label: 'addr_housenumber',
      size: 14.4,
      opacity: 0.6,
      lineWidth: 1,
      fadeNear: 0.9,
      fadeFar: 1,
    },
    {
      description: 'country border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['==', ['get', 'admin_level'], 2],
        ['==', ['get', '$geometryType'], 'line'],
      ],
      technique: 'solid-line',
      attr: {
        color: '#898989',
        lineWidth: [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          4000,
          3,
          2600,
          4,
          1500,
          5,
          1000,
          6,
          720,
          7,
          520,
          8,
          270,
          9,
          140,
          10,
          90,
          11,
          60,
          12,
          30,
          13,
          15,
          14,
          10,
          15,
          5,
          16,
          2,
        ],
      },
      renderOrder: 4.2,
    },
    {
      description: 'country border - labels',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['==', ['get', 'admin_level'], 2],
        ['==', ['get', '$geometryType'], 'line'],
      ],
      technique: 'text',
      attr: {
        priority: 100,
        color: '#000000',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 1,
        size: 12.8,
      },
    },
    {
      description: 'disputed border line',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['==', ['get', '$geometryType'], 'line'],
        ['>', ['get', 'admin_level'], 2],
      ],
      technique: 'dashed-line',
      attr: {
        color: '#7C7C7C',
        lineWidth: [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          4000,
          3,
          2600,
          4,
          1500,
          5,
          1000,
          6,
          720,
          7,
          520,
          8,
          270,
          9,
          140,
          10,
          90,
          11,
          60,
          12,
          30,
          13,
          15,
          14,
          10,
          15,
          5,
          16,
          2,
        ],
        dashSize: [
          'interpolate',
          ['cubic'],
          ['zoom'],
          10,
          1024,
          11,
          512,
          12,
          256,
          13,
          128,
          14,
          64,
        ],
        gapSize: [
          'interpolate',
          ['cubic'],
          ['zoom'],
          10,
          512,
          11,
          256,
          12,
          128,
          13,
          64,
          14,
          32,
        ],
      },
      renderOrder: 4.1,
    },
    {
      description: 'disputed border line - text',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['>', ['get', 'admin_level'], 2],
        ['==', ['get', '$geometryType'], 'line'],
      ],
      technique: 'text',
      attr: {
        priority: 100,
        color: '#000000',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.5,
        size: 12.8,
      },
    },
    {
      description: 'region border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['>', ['get', 'admin_level'], 4],

        ['==', ['get', '$geometryType'], 'line'],
      ],
      technique: 'solid-line',
      attr: {
        color: '#7C7C7C',
        lineWidth: [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          600,
          3,
          300,
          4,
          150,
          5,
          100,
          6,
          60,
          7,
          30,
          8,
          20,
          9,
          12,
          10,
          8,
          11,
          5,
          12,
          3,
          13,
          2,
          14,
          1,
        ],
      },
      renderOrder: 4.1,
    },
    {
      description: 'region border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['>', ['get', 'admin_level'], 4],
        // ["==", ["get", "class"], "region"]
        ['==', ['get', '$geometryType'], 'line'],
        // ["==", ["get", "kind"], "region"]
      ],
      technique: 'solid-line',
      attr: {
        color: '#7C7C7C',
        lineWidth: [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          600,
          3,
          300,
          4,
          150,
          5,
          100,
          6,
          60,
          7,
          30,
          8,
          20,
          9,
          12,
          10,
          8,
          11,
          5,
          12,
          3,
          13,
          2,
          14,
          1,
        ],
      },
      renderOrder: 4.1,
    },
    {
      description: 'region border',
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['>', ['get', 'admin_level'], 4],
        ["==", ["get", "class"], "region"],
        ["==", ["get", "$geometryType"], "line"],
        ["==", ["get", "kind"], "region"],
      ],
      technique: 'text',
      attr: {
        priority: 90,
        color: '#000000',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 1,
        size: 12.8,
      },
    },
    {
      when: [
        'all',
        ['==', ['get', '$layer'], 'boundary'],
        ['==', ['get', '$geometryType'], 'Point'],
      ],
      technique: 'text',
      attr: {
        color: '#000000',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.5,
        size: 27.2,
        priority: 200,
      },
      renderOrder: 7,
    },

    {
      description: 'country_pop_>10000000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'country'],
        // ["in", ["get", "kind"], ["country"]],
        // ["has", "population"],
        // [">", ["get", "population"], 10000000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],
        priority: 100,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          1,
          11.2,
          2,
          12.8,
          3,
          19.2,
          4,
          22.4,
          5,
          25.6,
        ],
        color: '#3F1821',
        backgroundColor: '#FFFFFF',
        // backgroundOpacity: 0.5,
        fontVariant: 'SmallCaps',
        // opacity: 0.8,
        // textFadeTime: 0.75,
        // fadeNear: 0.8,
        // fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'country_pop_>1000000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'country'],
        // ["in", ["get", "kind"], ["country"]],
        // ["has", "population"],
        // [">", ["get", "population"], 1000000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 100,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          1,
          8,
          2,
          9.6,
          3,
          12.8,
          4,
          16,
          5,
          19.2,
        ],
        color: '#3F1821',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 1,
        fontVariant: 'SmallCaps',
        opacity: 1,
        textFadeTime: 1,
        fadeNear: 1,
        fadeFar: 0,
      },
      final: true,
    },
    {
      description: 'country',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'country'],
        // ["in", ["get", "kind"], ["country"]]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 90,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          1,
          6.4,
          2,
          11.2,
          3,
          9.6,
          4,
          12.8,
          5,
          16,
        ],
        color: '#3F1922',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.5,
        fontVariant: 'SmallCaps',
        opacity: 0.8,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'Places',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'region'],
        // ["in", ["get", "kind"], ["region"]]
      ],
      technique: 'none',
      attr: {
        text: ['get', 'name:en'],

        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          9.6,
          4,
          10.88,
          5,
          12.8,
          6,
          14.4,
        ],
        priority: 65,
        color: '#060606',
        fontVariant: 'SmallCaps',
        opacity: 0.8,
        textFadeTime: 0.75,
        iconFadeTime: 0.5,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
    },
    {
      description: 'Places City',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'city'],
        // ["in", ["get", "kind"], ["region"]]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],
        fontStyle: 'Bold',
        priority: 61,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          9.6,
          4,
          10.88,
          5,
          12.8,
          6,
          14.4,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>10000000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'locality'],
        // ["==", ["get", "kind"], "locality"],
        // [
        //     "any",
        //     [">", ["number", ["get", "population"], 0], 10000000],
        //     ["has", "country_capital"]
        // ]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        fontStyle: 'Bold',
        priority: 61,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          1,
          9.6,
          2,
          11.2,
          3,
          12.8,
          4,
          14.4,
          5,
          16,
          6,
          19.2,
          7,
          22.4,
          8,
          25.6,
          9,
          28.8,
          10,
          32,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'town locality_pop_>10000000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'town'],
        // ["==", ["get", "kind"], "locality"],
        // [
        //     "any",
        //     [">", ["number", ["get", "population"], 0], 10000000],
        //     ["has", "country_capital"]
        // ]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        fontStyle: 'Bold',
        priority: 61,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          12.8,
          12,
          14.4,
          13,
          16,
          14,
          17.6,
          15,
          19.2,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>10000000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'locality'],
        // ["==", ["get", "kind"], "locality"],
        // [
        //     "any",
        //     [">", ["number", ["get", "population"], 0], 10000000],
        //     ["has", "country_capital"]
        // ]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 61,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          1,
          9.6,
          2,
          11.2,
          3,
          12.8,
          4,
          14.4,
          5,
          16,
          6,
          19.2,
          7,
          22.4,
          8,
          25.6,
          9,
          28.8,
          10,
          32,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>1000000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'locality'],
        // ["==", ["get", "kind"], "locality"],
        // [
        //     "any",
        //     [">", ["number", ["get", "population"], 0], 1000000],
        //     ["has", "region_capital"]
        // ]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 60,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          2,
          9.6,
          3,
          11.2,
          4,
          12.8,
          5,
          14.4,
          6,
          16,
          7,
          19.2,
          8,
          22.4,
          9,
          25.6,
          10,
          28.8,
          11,
          32,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>400000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'locality'],
        // ["==", ["get", "kind"], "locality"],
        // ["has", "population"],
        // [">", ["get", "population"], 400000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 59,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          4,
          11.2,
          5,
          12.8,
          6,
          16,
          7,
          19.2,
          8,
          22.4,
          9,
          24,
          10,
          25.6,
          11,
          27.2,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>100000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        // ["==", ["get", "kind"], "locality"],
        ['==', ['get', 'class'], 'locality'],
        // ["has", "population"],
        // [">", ["get", "population"], 100000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 58,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          4,
          9.6,
          5,
          11.2,
          6,
          12.8,
          7,
          16,
          8,
          19.2,
          9,
          20.8,
          10,
          22.4,
          11,
          24,
          12,
          25.6,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>50000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'locality'],
        // ["==", ["get", "kind"], "locality"],
        // ["has", "population"],
        // [">", ["get", "population"], 50000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 57,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          16,
          11,
          19.2,
          12,
          22.4,
          13,
          24,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_>10000',
      when: [
        'all',
        ['==', ['get', '$layer'], 'place'],
        ['==', ['get', 'class'], 'locality'],
        // ["==", ["get", "kind"], "locality"],
        // ["has", "population"],
        // [">", ["get", "population"], 10000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 56,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          16,
          12,
          17.6,
          13,
          19.2,
          14,
          20.8,
          15,
          22.4,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_<=10000',
      when: [
        'all',
        // ['==', ['get', '$layer'], 'place'],
        // ["==", ["get", "kind"], "locality"],
        // ['==', ['get', 'class'], 'locality'],
        // ["has", "population"],
        // ["<=", ["get", "population"], 10000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 50,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          12.8,
          12,
          14.4,
          13,
          16,
          14,
          17.6,
          15,
          19.2,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'village',
      when: [
        'all',
        // ['==', ['get', '$layer'], 'place'],
        // ["==", ["get", "kind"], "locality"],
        // ['==', ['get', 'class'], 'village'],
        // ["has", "population"],
        // ["<=", ["get", "population"], 10000]
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 50,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          12.8,
          12,
          14.4,
          13,
          16,
          14,
          17.6,
          15,
          19.2,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
    {
      description: 'locality_pop_<=10000',
      when: [
        'all',
        // ['==', ['get', '$layer'], 'place'],
        // ["==", ["get", "kind"], "locality"],
        // ['==', ['get', 'class'], 'island'],
        // ["has", "population"],
        // ["<=", ["get", "population"], 10],
      ],
      technique: 'text',
      attr: {
        text: ['get', 'name:en'],

        priority: 50,
        size: [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          12.8,
          12,
          14.4,
          13,
          16,
          14,
          17.6,
          15,
          19.2,
        ],
        color: '#090A0B',
        backgroundColor: '#FFFFFF',
        backgroundOpacity: 0.3,
        textFadeTime: 0.75,
        fadeNear: 0.8,
        fadeFar: 0.9,
      },
      final: true,
    },
  ],
};
