package com.micro.model.fake;

import com.alibaba.fastjson.annotation.JSONField;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

@Data
public class MotorVehicleListOut {
    @JSONField(name = "MotorVehicleList")
    private MotorVehicleListDTO motorVehicleListDTO;

    @Data
    public static class MotorVehicleListDTO implements Serializable {
        @JSONField(name = "MotorVehicleObject")
        public List<MotorVehicleObjectDTO> MotorVehicleObject;

        @Data
        public static class MotorVehicleObjectDTO implements Serializable {
            @JSONField(name = "MotorVehicleID")
            public String MotorVehicleID;
            @JSONField(name = "InfoKind")
            public Integer InfoKind;
            @JSONField(name = "SourceID")
            public String SourceID;
            @JSONField(name = "TollgateID")
            public String TollgateID;
            @JSONField(name = "DeviceID")
            public String DeviceID;
            @JSONField(name = "StorageUrl1")
            public String StorageUrl1;
            @JSONField(name = "StorageUrl2")
            public String StorageUrl2;
            @JSONField(name = "StorageUrl3")
            public String StorageUrl3;
            @JSONField(name = "StorageUrl4")
            public String StorageUrl4;
            @JSONField(name = "StorageUrl5")
            public String StorageUrl5;
            @JSONField(name = "LeftTopX")
            public Integer LeftTopX;
            @JSONField(name = "LeftTopY")
            public Integer LeftTopY;
            @JSONField(name = "RightBtmX")
            public Integer RightBtmX;
            @JSONField(name = "RightBtmY")
            public Integer RightBtmY;
            @JSONField(name = "LaneNo")
            public Integer LaneNo;
            @JSONField(name = "PlateClass")
            public String PlateClass;
            @JSONField(name = "PlateNo")
            public String PlateNo;
            @JSONField(name = "PlateNoAttach")
            public String PlateNoAttach;
            @JSONField(name = "PlateDescribe")
            public String PlateDescribe;
            @JSONField(name = "Speed")
            public Double Speed;
            @JSONField(name = "DrivingStatusCode")
            public String DrivingStatusCode;
            @JSONField(name = "VehicleClass")
            public String VehicleClass;
            @JSONField(name = "VehicleBrand")
            public String VehicleBrand;
            @JSONField(name = "VehicleLength")
            public Integer VehicleLength;
            @JSONField(name = "VehicleWidth")
            public Integer VehicleWidth;
            @JSONField(name = "VehicleHeight")
            public Integer VehicleHeight;
            @JSONField(name = "VehicleHood")
            public String VehicleHood;
            @JSONField(name = "VehicleTrunk")
            public String VehicleTrunk;
            @JSONField(name = "VehicleWheel")
            public String VehicleWheel;
            @JSONField(name = "WheelPrintedPattern")
            public String WheelPrintedPattern;
            @JSONField(name = "VehicleWindow")
            public String VehicleWindow;
            @JSONField(name = "VehicleRoof")
            public String VehicleRoof;
            @JSONField(name = "VehicleDoor")
            public String VehicleDoor;
            @JSONField(name = "SideOfVehicle")
            public String SideOfVehicle;
            @JSONField(name = "CarOfVehicle")
            public String CarOfVehicle;
            @JSONField(name = "RearviewMirror")
            public String RearviewMirror;
            @JSONField(name = "VehicleChassis")
            public String VehicleChassis;
            @JSONField(name = "VehicleShielding")
            public String VehicleShielding;
            @JSONField(name = "HitMarkInfo")
            public String HitMarkInfo;
            @JSONField(name = "VehicleBodyDesc")
            public String VehicleBodyDesc;
            @JSONField(name = "VehicleFrontItem")
            public String VehicleFrontItem;
            @JSONField(name = "DescOfFrontItem")
            public String DescOfFrontItem;
            @JSONField(name = "VehicleRearItem")
            public String VehicleRearItem;
            @JSONField(name = "DescOfRearItem")
            public String DescOfRearItem;
            @JSONField(name = "NumOfPassenger")
            public Integer NumOfPassenger;
            @JSONField(name = "NameOfPassedRoad")
            public String NameOfPassedRoad;
            @JSONField(name = "Sunvisor")
            public Integer Sunvisor;
            @JSONField(name = "SafetyBelt")
            public Integer SafetyBelt;
            @JSONField(name = "Calling")
            public Integer Calling;
            @JSONField(name = "PlateCharReliability")
            public String PlateCharReliability;
            @JSONField(name = "TabID")
            public String TabID;
            @JSONField(name = "NationalityCode")
            public String NationalityCode;
            @JSONField(name = "Similaritydegree")
            public Double Similaritydegree;
            @JSONField(name = "SourceType")
            public Integer SourceType;
            @JSONField(name = "SourceSender")
            public String SourceSender;
            @JSONField(name = "CollectorOrg")
            public String CollectorOrg;
            @JSONField(name = "CollectorID")
            public String CollectorID;
            @JSONField(name = "DeviceSNNo")
            public String DeviceSNNo;
            @JSONField(name = "APSId")
            public String APSId;
            @JSONField(name = "SourceFactory")
            public Integer SourceFactory;
            @JSONField(name = "VehicleSubBrand")
            public String VehicleSubBrand;
            @JSONField(name = "HasSunroof")
            public Integer HasSunroof;
            @JSONField(name = "HasRoofRacks")
            public Integer HasRoofRacks;
            @JSONField(name = "DeviceClass")
            public Integer DeviceClass;
            @JSONField(name = "PlateformIP")
            public String PlateformIP;
            @JSONField(name = "GroupID")
            public String GroupID;
            @JSONField(name = "PlateStructure")
            public String PlateStructure;
            @JSONField(name = "PlateLocation")
            public String PlateLocation;
            @JSONField(name = "PlateType")
            public String PlateType;
            @JSONField(name = "DataCompResult")
            public Integer DataCompResult;
            @JSONField(name = "ContainerNum1")
            public String ContainerNum1;
            @JSONField(name = "ContainerNum2")
            public String ContainerNum2;
            @JSONField(name = "WeighBridgeValue")
            public Integer WeighBridgeValue;
            @JSONField(name = "ReceiptNumber")
            public String ReceiptNumber;
            @JSONField(name = "UpdateMark")
            public Integer UpdateMark;
            @JSONField(name = "LinkFaceVehicleID")
            public String LinkFaceVehicleID;
            @JSONField(name = "LinkCoFaceVehicleID")
            public String LinkCoFaceVehicleID;
            @JSONField(name = "OriginID")
            public String OriginID;
            @JSONField(name = "IsECSB")
            public Integer IsECSB;
            @JSONField(name = "IsFirstData")
            public Integer IsFirstData;
            @JSONField(name = "SecondPlateNo")
            public String SecondPlateNo;
            @JSONField(name = "SecondVehicleBrand")
            public String SecondVehicleBrand;
            @JSONField(name = "SecondVehicleClass")
            public String SecondVehicleClass;
            @JSONField(name = "vicePilotSunvisor")
            public Integer vicePilotSunvisor;
            @JSONField(name = "dangmark")
            public Integer dangmark;
            @JSONField(name = "envprosign")
            public Integer envprosign;
            @JSONField(name = "tricycleCanopy")
            public Integer tricycleCanopy;
            @JSONField(name = "tempplateNo")
            public Integer tempplateNo;
            @JSONField(name = "pdvs")
            public Integer pdvs;
            @JSONField(name = "copilot")
            public Integer copilot;
            @JSONField(name = "decoration")
            public Integer decoration;
            @JSONField(name = "tissueBox")
            public Integer tissueBox;
            @JSONField(name = "frontChild")
            public Integer frontChild;
            @JSONField(name = "pendant")
            public Integer pendant;
            @JSONField(name = "muckTruck")
            public Integer muckTruck;
            @JSONField(name = "sunroof")
            public Integer sunroof;
            @JSONField(name = "luggageRack")
            public Integer luggageRack;
            @JSONField(name = "vehicleSprayPainted")
            public Integer vehicleSprayPainted;
            @JSONField(name = "vicePilotSafebelt")
            public Integer vicePilotSafebelt;
            @JSONField(name = "FrontRear")
            public Integer FrontRear;
            @JSONField(name = "LeftShield")
            public Integer LeftShield;
            @JSONField(name = "RightShield")
            public Integer RightShield;
            @JSONField(name = "RightSeated")
            public Integer RightSeated;
            @JSONField(name = "LeftBelt")
            public Integer LeftBelt;
            @JSONField(name = "RightBelt")
            public Integer RightBelt;
            @JSONField(name = "HasRoofWindow")
            public Integer HasRoofWindow;
            @JSONField(name = "IsChemical")
            public Integer IsChemical;
            @JSONField(name = "IsMuck")
            public Integer IsMuck;
            @JSONField(name = "HasPlate")
            public String HasPlate;
            @JSONField(name = "PlateColor")
            public String PlateColor;
            @JSONField(name = "IsDecked")
            public String IsDecked;
            @JSONField(name = "IsAltered")
            public String IsAltered;
            @JSONField(name = "IsCovered")
            public String IsCovered;
            @JSONField(name = "Direction")
            public String Direction;
            @JSONField(name = "VehicleColor")
            public String VehicleColor;
            @JSONField(name = "VehicleColorDepth")
            public String VehicleColorDepth;
            @JSONField(name = "FilmColor")
            public String FilmColor;
            @JSONField(name = "IsModified")
            public String IsModified;
            @JSONField(name = "PassTime")
            public String PassTime;
            @JSONField(name = "IsSuspicious")
            public String IsSuspicious;
            @JSONField(name = "PlateReliability")
            public String PlateReliability;
            @JSONField(name = "BrandReliability")
            public String BrandReliability;
            @JSONField(name = "ShotPlaceLongitude")
            public Double ShotPlaceLongitude;
            @JSONField(name = "ShotPlaceLatitude")
            public Double ShotPlaceLatitude;
            @JSONField(name = "PlaceCode")
            public String PlaceCode;
            @JSONField(name = "ProvinceCode")
            public String ProvinceCode;
            @JSONField(name = "CityCode")
            public String CityCode;
            @JSONField(name = "SecondPlateColor")
            public String SecondPlateColor;
            @JSONField(name = "Longitude")
            public Double Longitude;
            @JSONField(name = "Latitude")
            public Double Latitude;
            @JSONField(name = "SubImageList")
            public SubImageListDTO SubImageList;

            @JSONField(name = "VehicleModel")
            public String VehicleModel;

            @JSONField(name = "VehicleStyles")
            public String VehicleStyles;


            @Data
            public static class SubImageListDTO implements Serializable {
                @JSONField(name = "SubImageInfoObject")
                public List<SubImageInfoObjectDTO> SubImageInfoObject;

                @Data
                public static class SubImageInfoObjectDTO implements Serializable {
                    @JSONField(name = "ImageID")
                    public String ImageID;
                    @JSONField(name = "EventSort")
                    public Integer EventSort;
                    @JSONField(name = "DeviceID")
                    public String DeviceID;
                    @JSONField(name = "StoragePath")
                    public String StoragePath;
                    @JSONField(name = "Type")
                    public String Type;
                    @JSONField(name = "FileFormat")
                    public String FileFormat;
                    @JSONField(name = "Width")
                    public Integer Width;
                    @JSONField(name = "Height")
                    public Integer Height;
                    @JSONField(name = "SelfDefData")
                    public String SelfDefData;
                    @JSONField(name = "AlgorithmsStatus")
                    public Integer AlgorithmsStatus;
                    @JSONField(name = "Score")
                    public Double Score;
                    @JSONField(name = "FileHash")
                    public String FileHash;
                    @JSONField(name = "ShotTime")
                    public String ShotTime;
                }
            }
        }
    }
}
